font_family      JetBrains Mono Nerd Font
font_size 11.0

cursor_shape beam
cursor_trail 1

shell zsh

background_opacity 0.8

background #101517
foreground #d8dee9
selection_background #434c5e
selection_foreground #d8dee9
cursor #d8dee9
cursor_text_color #2e3440
