set color_cmdline_bg=default
set color_cmdline_fg=#c0caf5

set color_separator=#1f2335

set color_statusline_bg=#292e42
set color_statusline_fg=#a9b1d6

set color_titleline_bg=#1f2335
set color_titleline_fg=#7aa2f7

set color_win_bg=default
set color_win_fg=#c0caf5
set color_win_cur=#7dcfff
set color_win_dir=#ff9e64

set color_win_inactive_cur_sel_bg=default
set color_win_inactive_cur_sel_fg=#565f89

set color_win_inactive_sel_bg=default
set color_win_inactive_sel_fg=#565f89

set color_win_cur_sel_bg=#2e3c64
set color_win_cur_sel_fg=#c0caf5

set color_win_sel_bg=#292e42
set color_win_sel_fg=#c0caf5

set color_win_title_bg=#1f2335
set color_win_title_fg=#7aa2f7

set color_error=#f7768e
set color_info=#9ece6a
