# ============================================================================
# fcitx5 标点符号配置
# ============================================================================

# 字母或者数字之后输入半角标点
HalfWidthPuncAfterLetterOrNumber=True
# 同时输入成对标点 (例如引号)
TypePairedPunctuationsTogether=False
# 启用标点符号处理
Enabled=True

[Hotkey]
0=Control+period   # 半角/全角标点切换快捷键
