set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides '*:Ss\x1b[%d q:Se\x1b[2 q'

set -g history-limit 10000
set -g mouse on
set -g escape-time 0

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g set-titles on
set -g set-titles-string "#T"
set -g display-panes-time 4000

set -g prefix C-b
unbind C-space
bind , command-prompt "rename-window '%%'"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind r source-file ~/.tmux.conf \; display "Config reloaded!"

set -g @tokyo-night-tmux_theme "storm"
set -g @tokyo-night-tmux_transparent 0

set -g @tokyo-night-tmux_show_git 1
set -g @tokyo-night-tmux_show_path 1
set -g @tokyo-night-tmux_show_hostname 0
set -g @tokyo-night-tmux_show_battery_widget 1

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'off'
set -g @continuum-save-interval '0'
set -g @plugin 'janoamaral/tokyo-night-tmux'

bind s run "~/.tmux/plugins/tmux-resurrect/scripts/save.sh"
bind S run "~/.tmux/plugins/tmux-resurrect/scripts/restore.sh"

run '~/.tmux/plugins/tpm/tpm'

# 去掉状态栏右侧组件，只保留左侧窗口列表
set -g status-right ""
