[ColorScheme]
# Catppuccin Mocha (mauve) Qt6 Palette
# 顺序 = Qt ColorRole: WindowText, Button, Light, Midlight, Dark, Mid,
#   Text, BrightText, ButtonText, Base, Window, Shadow, Highlight,
#   HighlightedText, Link, LinkVisited, AlternateBase, NoRole,
#   ToolTipBase, ToolTipText, PlaceholderText
active_colors=#ffcdd6f4, #ff45475a, #ff585b70, #ff45475a, #ff313244, #ff313244, #ffcdd6f4, #ffffffff, #ffcdd6f4, #ff1e1e2e, #ff313244, #ff11111b, #ffcba6f7, #ff1e1e2e, #ff89b4fa, #ffb4befe, #ff313244, #ffcdd6f4, #ff313244, #ffcdd6f4, #ff6c7086
disabled_colors=#ff6c7086, #ff45475a, #ff585b70, #ff45475a, #ff313244, #ff313244, #ff6c7086, #ff313244, #ff6c7086, #ff1e1e2e, #ff313244, #ff11111b, #ffcba6f7, #ff1e1e2e, #ff89b4fa, #ffb4befe, #ff313244, #ff6c7086, #ff313244, #ffcdd6f4, #ff6c7086
inactive_colors=#ffcdd6f4, #ff45475a, #ff585b70, #ff45475a, #ff313244, #ff313244, #ffcdd6f4, #ffffffff, #ffcdd6f4, #ff1e1e2e, #ff313244, #ff11111b, #ffcba6f7, #ff1e1e2e, #ff89b4fa, #ffb4befe, #ff313244, #ffcdd6f4, #ff313244, #ffcdd6f4, #ff6c7086
